# Generated by Django 4.1.3 on 2022-11-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srkauth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
