# Generated by Django 4.1.3 on 2022-11-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srkapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateprofile',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
