# Generated by Django 4.1.3 on 2022-11-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srkapp', '0002_updateprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateprofile',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
