# Generated by Django 4.1.3 on 2022-11-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srkapp', '0003_updateprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=50)),
                ('fathername', models.CharField(default='', max_length=50)),
                ('mothername', models.CharField(default='', max_length=50)),
                ('ssc', models.CharField(default='', max_length=50)),
                ('inter', models.CharField(default='', max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('spec', models.CharField(max_length=50)),
            ],
        ),
    ]
