# Generated by Django 4.1.3 on 2022-11-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srkapp', '0004_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
