# Generated by Django 4.1.3 on 2022-12-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srkapp', '0007_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
