# Generated by Django 4.1.3 on 2022-12-01 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srkapp', '0008_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='num',
        ),
    ]
