# Generated by Django 4.1.3 on 2022-12-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srkapp', '0009_rename_description_contact_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('date', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('work', models.CharField(default='', max_length=50)),
                ('experience', models.CharField(default='', max_length=50)),
                ('graduatedat', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
