# Generated by Django 4.1.3 on 2022-12-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srkapp', '0010_apply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='experience',
            new_name='expierence',
        ),
    ]
